module.exports = {
  GET_STORE: 'get-store',
  GET_STORE_DATA: 'get-store-data',
  LOGIN_USER: 'login-user',
  IS_AUTHENTICATE: 'is-authenticate',
  IS_AUTHENTICATE_REPLY: 'is-authenticate-reply',
  GET_TOYATA_DATA: 'get-toyota-data',
  GET_TOYATA_DATA_REPLY: 'get-toyota-data-reply',
  GET_DB: 'get-db',
  GET_DB_REPLY: 'get-db-reply',
  SERACH_PARTS: 'search-parts',
  PRINT_TO_PDF: 'print-to-pdf',
  ADD_PART_TO_CART: 'add-part-to-cart',
  UPDATE_PART_FROM_CART: 'update-part-from-cart',
  DELETE_PART_FROM_CART: 'delete-part-from-cart',
  EMPTY_CART: 'empty-cart',
  BROADCAST_CART_TO_COMPONENT: 'broadcast-cart-to-component',
  SERACH_ORDERS: 'search-orders',
}